# Generated by Django 3.2.5 on 2021-07-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_habitentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitentry',
            name='created_at',
        ),
    ]
