# Generated by Django 3.2.5 on 2021-07-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210712_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
