# Generated by Django 3.2.5 on 2021-07-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_habitentry_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitentry',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.AddConstraint(
            model_name='habitentry',
            constraint=models.UniqueConstraint(fields=('habit',), name='just_one_habit'),
        ),
    ]
